### ISSUE TITLE
`yakumo upgrade` 忽略某个(些)工作区执行更新

### ISSUE THREAD

**Issue by CyanChanges** [shigma/yakumo#15]
### 需求

`yakumo upgrade` 支持忽略某些 workspace 或者文件夹更新依赖

### 原因

将 koishijs/koishi 和 koishijs/webui clone 到本地之后, 
`yakumo upgrade` 会也会将这两个 repo 的依赖更新.

就会导致我在用 idea Commit & Push 我的插件的时候, 
push 到 `koishijs/koishi` `koishijs/webui`, 然后就 403 了, 
后来, 我将本地的上游改到我 fork 的 koishi 和 webui

但是, 
后续接受 `koishijs/koishi` 和 `koishijs/webui` 上游修改的时候,
需要手动 Merge 或确认 Rebase (Discard Changes).
不 Commit 也会因为本地有修改导致无法直接拉取 
<sup>(而且找哪些文件是 koishi/webui repo 的挺麻烦的)</sup>
还得 stash 或者 restore

如果 yakumo 支持忽略某些文件夹的 upgrade 依赖,
就不会出现类似问题

**Comment by CyanChanges** [comment]
https://github.com/cordiverse/yakumo/pull/18

**Comment by shigma** [comment]
这个可以做，不过改动可能导致 breaking change，我先描述一下做法。

全部指令忽略特定工作区：

```yaml
- name: yakumo
  config:
    exclude:
      - path/to/package
```

特定指令忽略全部工作区（除了 root）：

```yaml
- name: yakumo
- name: yakumo/upgrade
  intercept:
    yakumo:
      exclude:
        - *
```

这个改动依赖一件事，就是把 yakumo 的插件重新导出，下放到配置文件中，这样才能允许 intercept 写法。

稍后我来进行这个改动。
